version: '2'
services:
  hugo-api-server:
    build: .
    volumes:
      - ./api:/work/api
      - ./blog:/work/blog
    ports:
      - "8000:8000"
    working_dir: /work/api
    command: python3 -u server.py -m prob
    # tty : true

  hugo-web-server:
    image: nginx:1.15.5-alpine
    ports:
      - 80:80
    volumes:
      - ./blog/public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/key:/etc/nginx/key
    tty : true

  # frontend:
  #   image: nginx:1.15.5-alpine
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./front-nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./front-nginx/nginx.conf:/etc/nginx/nginx.conf
  #   tty : true
  #   links:
  #     - hugo-web-server
